name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"

# 포함된 label에 따라서 title을 변경
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
  - title: "🧰 Maintenance"
    label: "chore"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add `

# 포함된 label에 따라 릴리즈 버전을 관리
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

template: |
  ## What’s Changed
  $CHANGES
