name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    - name: echo args
      run: echo "release"
  create-tag:
    needs: release
    if: success()
    uses: ./.github/workflows/create-release.yml