name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: echo args
        run: echo "release"
  create-release-note:
    needs: release
    if: success()
    uses: ./.github/workflows/create-release-note.yml
