name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-tag:
    name: get New Tag from branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: 버전 정보 추출
        run: echo "tag=v$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_ENV
        id: extract_version_name
      - name: validate-tag
        uses: bbonkr/git-tag-check-action@v1.0.5
        id: git_tag_check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ env.tag }}"
      - name: logging found
        if: ${{ steps.git_tag_check.outputs.tag != '' }}
        run: |
          echo "::error ${{ steps.git_tag_check.outputs.tag }} is already exists"
  release:
    name: deploy to S3
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: echo args
        run: echo "release"
  create-release-note:
    needs: [create-tag, release]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          tag: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
