name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-tag:
    name: get New Tag from branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: 버전 정보 추출
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name
      - name: validate-tag
        uses: bbonkr/git-tag-check-action@v1.0.5
        id: git_tag_check
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version_name.outputs.version }}
      - name: logging found
        if: ${{ steps.git_tag_check.outputs.tag != '' }}
        run: |
          echo "Found tag=${{ steps.git_tag_check.outputs.tag }}"
      - name: logging not found
        if: ${{ steps.git_tag_check.outputs.tag == '' }}
        run: |
          echo "Tag does not exist"
  release:
    name: deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: echo args
        run: echo "release"
      - name: create-release-note
        uses: ./.github/workflows/create-release-note.yml
