name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: echo args
        run: echo "release"
  create-release-note:
    needs: release
    if: success()
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    uses: ./.github/workflows/create-release-note.yml
