name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  runs-on: ubuntu-latest
  create-tag:
    name: get New Tag from branch
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: 버전 정보 추출
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
        id: extract_version_name
  vaildate-tag:
    uses: ./.github/workflows/validate-tag.yml
    with:
      tag_name: ${{ create-tag.steps.extract_version_name.outputs.version }}
  release:
    name: deploy to S3
    runs-on: ubuntu-latest
    steps:
      - name: echo args
        run: echo "release"
  create-release-note:
    needs: release
    if: success()
    uses: ./.github/workflows/create-release-note.yml
