name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: deploy to S3
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - name: echo args
        run: echo "release"
  create-release-note:
    needs: [create-tag, release]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          tag: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
