name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Check and Release New Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Detect and Tag New Version을 위해 필요
          fetch-depth: 2

      - name: Publish Release Notes
        if: steps.check-version.outputs.tag
        # We can switch to a tagged version once 5.8 is published
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
          tag: "1.1.1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
